/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniImage */

#ifndef _Included_JniImage
#define _Included_JniImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniImage
 * Method:    setPixelsJni
 * Signature: ([[LPixel;)J
 */
JNIEXPORT jlong JNICALL Java_JniImage_setPixelsJni
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     JniImage
 * Method:    getPixelsJni
 * Signature: (J)[[LPixel;
 */
JNIEXPORT jobjectArray JNICALL Java_JniImage_getPixelsJni
  (JNIEnv *, jobject, jlong);

/*
 * Class:     JniImage
 * Method:    getPixelJni
 * Signature: (JII)LPixel;
 */
JNIEXPORT jobject JNICALL Java_JniImage_getPixelJni
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     JniImage
 * Method:    setPixelJni
 * Signature: (JIILPixel;)V
 */
JNIEXPORT void JNICALL Java_JniImage_setPixelJni
  (JNIEnv *, jobject, jlong, jint, jint, jobject);

/*
 * Class:     JniImage
 * Method:    blurJni
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_JniImage_blurJni
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     JniImage
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_JniImage_destroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
